### PR TITLE
internal: replace difference with similar

### PR DESCRIPTION
**Pull request by tommilligan**
See #44 

Major rewrite to remove the dependency on `difference`, which is unmaintained.

### CODE REVIEW

**Comment by tommilligan** [comment]
@mitsuhiko I've benchmarked this branch vs `main` using the benchmarks [here](https://github.com/tommilligan/rust-pretty-assertions-bench), unfortunately there appear to be some performance regressions for writing the diff:

image

I'm going to continue investigating, but this means I'm unlikely to merge this implementation as is.

**Comment by tommilligan** [comment]
Closing for now as obsolete from #52, happy to revisit if the performance can be improved.

**Comment by mitsuhiko** [comment]
Thanks for the heads up. I will add some benchmarks to figure out what’s going on.

**Comment by mitsuhiko** [comment]
@tommilligan I'm not sure yet why myers performs so bad but I added a simple LCS implementation to see how it performs. I noticed two things from this:

- `iter_all_changes` internally needs to call `Box::new` for stupid lifetime reasons I can't figure out. You get a small performance benefit by calling `ops + iter_changes` yourself.
- next version of `similar` comes with `Lcs` you can use like this:

```rust
    let diff = TextDiff::configure()
        .algorithm(Algorithm::Lcs)
        .diff_lines(left, right);
```

Both of those together are similar in performance to the current main version of rust-pretty-assertions. Sadly I'm on a laptop so I can't do stable benchmarks here.

**Comment by mitsuhiko** [comment]
Pushed out a 1.2.0 with the changes. And thanks for the box fix.

**Pull request closed without merging**
